# Generated by Django 2.1.2 on 2018-12-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0002_game_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
