# Generated by Django 2.1.2 on 2018-12-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0004_auto_20181221_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='passcode',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
