# Generated by Django 2.1.2 on 2018-12-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0006_game_passcode_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='num_joined',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
