# Generated by Django 2.1.2 on 2018-12-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0007_auto_20181221_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
