# Generated by Django 2.1.2 on 2019-01-08 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0012_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='smear.Game'),
        ),
    ]
