# Generated by Django 2.1.2 on 2019-01-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0013_auto_20190108_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='single_player',
            field=models.BooleanField(default=True),
        ),
    ]
