# Generated by Django 2.1.2 on 2019-01-10 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smear', '0015_auto_20190110_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(through='smear.Player', to=settings.AUTH_USER_MODEL),
        ),
    ]
