# Generated by Django 2.1.2 on 2019-02-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0019_auto_20190129_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
