# Generated by Django 2.1.2 on 2019-03-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0023_auto_20190312_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='trump',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
