# Generated by Django 2.1.2 on 2019-03-21 05:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0024_bid_trump'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cards_played', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2), default=list, size=None)),
                ('active_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tricks_playing', to='smear.Player')),
            ],
        ),
        migrations.AddField(
            model_name='hand',
            name='high_card',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='hand',
            name='low_card',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='hand',
            name='winner_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_winner_game', to='smear.Player'),
        ),
        migrations.AddField(
            model_name='hand',
            name='winner_high',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_winner_high', to='smear.Player'),
        ),
        migrations.AddField(
            model_name='hand',
            name='winner_jack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_winner_jack', to='smear.Player'),
        ),
        migrations.AddField(
            model_name='hand',
            name='winner_jick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_winner_jick', to='smear.Player'),
        ),
        migrations.AddField(
            model_name='hand',
            name='winner_low',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_winner_low', to='smear.Player'),
        ),
        migrations.AddField(
            model_name='trick',
            name='hand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tricks', to='smear.Hand'),
        ),
    ]
