# Generated by Django 3.0.5 on 2020-04-29 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0025_auto_20190321_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='next_dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_next_dealer', to='smear.Player'),
        ),
    ]
