# Generated by Django 3.0.5 on 2020-04-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0026_game_next_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='trump',
            field=models.CharField(blank=True, choices=[], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='hand',
            name='trump',
            field=models.CharField(blank=True, choices=[('spades', 'spades'), ('hearts', 'hearts'), ('clubs', 'clubs'), ('diamonds', 'diamonds')], default='', max_length=16),
        ),
    ]
