# Generated by Django 3.0.5 on 2020-05-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        Trick = apps.get_model("smear", "Trick")
        Hand = apps.get_model("smear", "Hand")
        Game = apps.get_model("smear", "Game")

        for game in Game.objects.all():
            hnum = 1
            for hand in game.hands.filter(num=0):
                tnum = 1
                for trick in hand.tricks.filter(num=0):
                    trick.num = tnum
                    trick.save()
                    tnum += 1
                hand.num = hnum
                hand.save()
                hnum += 1

    def reverse_func(apps, schema_editor):
        Trick = apps.get_model("smear", "Trick")
        Hand = apps.get_model("smear", "Hand")

        Hand.objects.update(num=0)
        Trick.objects.update(num=0)

    dependencies = [
        ('smear', '0028_auto_20200504_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trick',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterUniqueTogether(
            name='hand',
            unique_together={('game', 'num')},
        ),
        migrations.AlterUniqueTogether(
            name='trick',
            unique_together={('hand', 'num')},
        ),
    ]
