# Generated by Django 3.0.5 on 2020-05-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0029_add_num_to_trick_and_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='taker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tricks_taken', to='smear.Player'),
        ),
    ]
