# Generated by Django 3.0.5 on 2020-05-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0030_trick_taker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hand',
            name='high_card',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='low_card',
        ),
        migrations.AddField(
            model_name='player',
            name='current_hand_game_points_won',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
