# Generated by Django 3.0.5 on 2020-05-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0031_auto_20200528_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
