# Generated by Django 3.0.5 on 2020-06-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0032_auto_20200528_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='winner',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='winner',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
