# Generated by Django 4.1.2 on 2022-11-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0034_alter_hand_options_alter_play_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='players_out_of_suits',
            field=models.JSONField(default=dict),
        ),
    ]
