# Generated by Django 4.1.2 on 2022-12-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0036_hand_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='prev_hand_game_points_won',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
