# Generated by Django 4.1.2 on 2023-12-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0037_player_prev_hand_game_points_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
