# Generated by Django 4.1.2 on 2023-12-15 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smear', '0038_team_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to='smear.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='next_dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_next_dealer', to='smear.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hand',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hands_was_bidder', to='smear.player'),
        ),
        migrations.AlterField(
            model_name='hand',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smear.player'),
        ),
        migrations.AlterField(
            model_name='hand',
            name='winner_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_winner_game', to='smear.player'),
        ),
        migrations.AlterField(
            model_name='hand',
            name='winner_high',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_winner_high', to='smear.player'),
        ),
        migrations.AlterField(
            model_name='hand',
            name='winner_jack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_winner_jack', to='smear.player'),
        ),
        migrations.AlterField(
            model_name='hand',
            name='winner_jick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_winner_jick', to='smear.player'),
        ),
        migrations.AlterField(
            model_name='hand',
            name='winner_low',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_winner_low', to='smear.player'),
        ),
        migrations.AlterField(
            model_name='play',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plays', to='smear.player'),
        ),
        migrations.AlterField(
            model_name='trick',
            name='active_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tricks_playing', to='smear.player'),
        ),
        migrations.AlterField(
            model_name='trick',
            name='taker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tricks_taken', to='smear.player'),
        ),
    ]
