# Generated by Django 4.1.2 on 2024-01-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0039_alter_bid_player_alter_game_next_dealer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_hand_game_points_won',
        ),
        migrations.RemoveField(
            model_name='player',
            name='prev_hand_game_points_won',
        ),
        migrations.AddField(
            model_name='hand',
            name='game_points_by_player',
            field=models.JSONField(default=dict),
        ),
    ]
