# Generated by Django 4.1.2 on 2024-02-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0041_game_scores_by_contestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='must_bid_to_win',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
