# Generated by Django 5.0.2 on 2024-04-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0042_game_must_bid_to_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='auto_pilot_mode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
