# Generated by Django 5.1.7 on 2025-05-02 01:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smear', '0043_player_auto_pilot_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_ids_in_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
