repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: ["-l", "120", "--target-version", "py310"]
        language_version: python3.10
        exclude: migrations
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: migrations
        args: [--config, backend/.flake8]
  - repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
      - id: isort
        args: [-l 120]
        name: isort (python)
        exclude: migrations
