version: '3'
services:
  api:
    build:
        context: ./
        dockerfile: Dockerfile
    command: python manage.py runserver --nostatic 0.0.0.0:8008
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8008:8008"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/playsmear
      - ENVIRON=local
      - DJANGO_SETTINGS_MODULE=api.settings.local
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: playsmear
