version: '3'
services:
  api:
    build:
        context: ./
        dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/playsmear
      - ENVIRON=local
      - DJANGO_SETTINGS_MODULE=api.settings.local
      - SENDGRID_API_KEY=no.key.localhost
      - TAWK_KEY=abc123
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: playsmear
