version: '3'
services:
  api:
    build:
        context: ./
        dockerfile: docker/api/Dockerfile
    command: python manage.py runserver 0.0.0.0:8008
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8008:8008"
    environment:
      - DATABASE_URL=postgres://postgres@postgres:5432/playsmear
      - ENVIRON=local
      - DJANGO_SETTINGS_MODULE=api.settings.local
#  ui:
#    build:
#        context: ./
#        dockerfile: docker/ui/Dockerfile
#    command: yarn start
#    volumes:
#      - .:/usr/src/app
#    ports:
#      - "3000:3000"
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: playsmear
