version: '3'
services:
    front_end:
        build: docker/front_end
        ports:
            - "4200:4200"
        volumes:
            - .:/play_smear
    back_end:
        build: docker/back_end
        ports:
            - "5000:5000"
        volumes:
            - .:/play_smear
        environment:
            - MONGODB_URI=mongodb://mongo/smear
            - MAILGUN_KEY=key-c0b496a8eab8ca86a3b4508547dcdbda
    mongo:
        image: mongo:latest
        ports:
            - "27017:27017"
